logging:
  level:
    com.makesoft.app: DEBUG

server:
  port: 8080
  address: 0.0.0.0  # Allow connections from all network interfaces (not just localhost)

spring:
  application:
    name: makesoft-backend