logging:
  level:
    com.makesoft.app: DEBUG

server:
  port: 8081
  address: 0.0.0.0  # Allow connections from all network interfaces (not just localhost)

spring:
  application:
    name: makesoft-backend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/your_database}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true